name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          echo "Building..."
          npm install
          npm run-script index
        env:
          RAZORPAY_SECRET: ${{secrets.RAZORPAY_SECRET}}
          RAZORPAY_KEY_ID: ${{secrets.RAZORPAY_KEY_ID}}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          folder: public