name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        APIKey: ${{ secrets.APIKey }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build 
